[package]
name = "web-scraper"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
reqwest = "0.12.12"
scraper = "0.23.1"
regex = "1.11.1"
axum = "0.8.1"
